[template]
cargo_generate_version = "0.22"
include = ["*.template"]
ignore = [
    ".github/workflows/ci-generate.yaml",
    "LICENSE-Apache-2.0.txt",
    "LICENSE-CC0-1.0.txt",
    "LICENSE-MIT.txt",
    "README.md",
]

[hooks]
post = ["post-generate.rhai"]
